### ISSUE TITLE
SpringBoot Integration

### ISSUE THREAD

**Issue by buzdin** [DozerMapper/dozer#480] opened 2017-08-22 12:22 UTC
There is a simple Spring Framework integration, however Spring Boot allows a more sophisticated plugin approach. It is possible to configure DozerMapper beans on startup by putting annotation on configuration class @EnableDozerMapper. This would enable all convention based settings.

This approach could be investigated and implemented.

**Comment by garethahealy** [comment] 2017-08-22 16:17
Duplicate of:
- https://github.com/DozerMapper/dozer/issues/382

**Comment by vadeg** [comment] 2017-10-22 16:05
Maybe it is better to close this ticket if it is a duplicate?

**Closed** 2017-10-23 06:26 UTC
