### ISSUE TITLE
Mapping from Map.class to Object not working as expected

### ISSUE THREAD

**Issue by jsbxyyx** [DozerMapper/dozer#588] opened 2018-04-03 09:50 UTC
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: 5.5.1
* OS version: window10
* JDK version: 1.8
  
## Whats the problem?
_Steps to reproduce:_
1. public class A {
private String date;
private String cmd;
private String vNum;
// getter setter toString
}
2. build a map
Map<String, String> map = new HashMap<>();
map.put("date", "2018-04-03");
map.put("cmd", "opt");
map.put("vNum", "123456")
3. dozer map operation
DozerBeanMapper dozer = new DozerBeanMapper();
A a = dozer.map(map, A.class);
  
### Observed Results:
_What happened?  This could be a description, log output, etc._
  
### Expected Results:
_What did you expect to happen?_
I want a = {date=2018-04-03, cmd=opt, vNum=123456}
but a =  {date=2018-04-03, cmd=opt, vNum=}

## Link to GitHub repo with Unit test
_The easiest way for us to fix issues, is if you provide a GitHub repo, using the latest release and a simple unit test._

**Comment by garethahealy** [comment] 2018-04-03 09:54
@jsbxyyx ; please see these tests, which should show you how to do what you need:
- https://github.com/DozerMapper/dozer/blob/c0de047a7073d7366fa883f0c7667027df25aacb/core/src/test/java/com/github/dozermapper/core/functional_tests/MapBackedDeepMappingTest.java

**Comment by jsbxyyx** [comment] 2018-04-03 10:55
@garethahealy 

public class A {
private String date;
private String cmd;
private String vaNum;
// getter setter toString
}

build a map
Map<String, String> map = new HashMap<>();
map.put("date", "2018-04-03");
map.put("cmd", "opt");
map.put("vaNum", "123456")

DozerBeanMapper dozer = new DozerBeanMapper();
A a = dozer.map(map, A.class);

I want a = {date=2018-04-03, cmd=opt, vaNum=123456}
expect {date=2018-04-03, cmd=opt, vaNum=123456}

why vNum not expect
but vaNum expect

**Comment by garethahealy** [comment] 2018-04-03 11:02
@jsbxyyx ; i dont understand your last comment...

**Comment by jsbxyyx** [comment] 2018-04-03 11:13
@garethahealy 
I am speak english a little

I mean to 
the A class use vNum field mapping fail
but the A class use vaNum field mapping success

are you ok???

**Comment by garethahealy** [comment] 2018-04-03 11:15
OK, its only a key, so it shouldn't matter if its vaNum or vNum.

Can you create a github repo, with a single JUnit test case, showing both vaNum and vNum? I can then debug to see what is wrong.

**Comment by jsbxyyx** [comment] 2018-04-03 11:30
@garethahealy 
you see example
https://github.com/jsbxyyx/dozer-test.git

**Comment by garethahealy** [comment] 2018-04-03 19:56
@jsbxyyx ; please see the following:
- https://stackoverflow.com/questions/40822397/why-does-propertydescriptor-return-a-property-name-with-uppercase-as-first-chara

As stated, its how the JDK works when looking up the properties, and as such, desired behaviour.

**Comment by jsbxyyx** [comment] 2018-04-04 01:14
@garethahealy 
The A class and A1 class getter setter I use lombok auto build, I find getter setter not standard javabean, so mapping fails

**Comment by jsbxyyx** [comment] 2018-04-04 06:40
@garethahealy 
I use java decoder tool decode A class to java source, then create dozer-test project to you.
so you are right.

**Comment by garethahealy** [comment] 2018-04-04 07:01
But the problem is still the same. The generated getters/setters by lombok, conform to how java expects. So since you have vNum, thats converted into VNum, which causes dozer to miss the mapping.

**Comment by jsbxyyx** [comment] 2018-04-04 07:15
@garethahealy 
## **right getters/setters**
```java
public class A {
private String vNum;
public void setvNum(String vNum) {
    this.vNum=vNum;
}
public String getvNum() {
    return vNum;
}
}
```
~error getters/setters~
```java
public class A {
private String vNum;
public void setVNum(String vNum) {
    this.vNum=vNum;
}
public String getVNum() {
    return vNum;
}
}
```
the question must be lombok 1.16.14 build setters/getters is not by Java Beans specification. or is lombok library bug.

**Comment by garethahealy** [comment] 2018-04-04 07:41
I've looked a bit further into this. If you were mapping a POJO -> POJO, then this would work. But because you are mapping an Map to POJO, and the Map generator doesn't support different case for keys, it miss matches.

- https://github.com/DozerMapper/dozer/tree/c0de047a7073d7366fa883f0c7667027df25aacb/core/src/main/java/com/github/dozermapper/core/classmap/generator

Currently, this isnt a bug, but maybe a lacking feature - not 100% sure if its possible either. needs more investigation.

**Comment by garethahealy** [comment] 2018-04-04 07:43
Closing, as 590 is the ticket that might fix this feature request.

**Closed by garethahealy** 2018-04-04 07:43 UTC
Labels: not-a-bug
