### ISSUE TITLE
is-accessible in global configuration

### ISSUE THREAD

**Issue by ArneLimburg** [DozerMapper/dozer#278] opened 2015-12-14 22:01 UTC
Hi,
is-accessible is defined class- and field-level, so is there any reason, that it is not available in global configuration? If no, consider this a feature request ;-)

**Comment by openwms** [comment] 2016-02-18 18:06
+1. same as here #271.

**Comment by Ice3ider** [comment] 2016-02-19 14:37
+1

**Comment by kamaydeo** [comment] 2016-05-13 15:28
+1

**Comment by garethahealy** [comment] 2017-04-05 12:45
Closing as duplicate of #271

**Closed by garethahealy** 2017-04-05 12:45 UTC
