### ISSUE TITLE
ClassNotFound Exception with classes of my own project 5.5.1

### ISSUE THREAD

**Issue by cdparra** [DozerMapper/dozer#261] opened 2015-09-15 05:42 UTC
I am developing a project using [playframework](https://www.playframework.com/) and when I try to use dozer for some mappings, I get a ClassNotFoundException with classes that are part of my own project. I suspect it has something to do with the class loader (as explained [here](http://stackoverflow.com/questions/23522072/dozer-classnotfoundexception-in-osgi-environment)) of play, which might not be compatible with this version (even though when using dozer 5.4.0 I have no problem at all) 

```
[info] play.api.Play$ - Application started (Dev)
[info] o.d.DozerBeanMapper - Initializing a new instance of dozer bean mapper.
[info] o.d.DozerBeanMapper - Using the following xml files to load custom mappings for the bean mapper instance: [dozerMapping.xml]
[info] o.d.DozerBeanMapper - Trying to find xml mapping file: dozerMapping.xml
[info] o.d.DozerBeanMapper - Using URL [file:/Users/cdparra/Projects/appcivist/appcivist-platform/target/scala-2.11/classes/dozerMapping.xml] to load custom xml mappings
[error] o.d.l.x.MappingStreamReader - Error while loading dozer mapping InputStream: [java.io.BufferedInputStream@1fd14bad]
org.dozer.MappingException: java.lang.ClassNotFoundException: models.location.Location
    at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:82) ~[dozer-5.5.1.jar:na]
    at org.dozer.util.DefaultClassLoader.loadClass(DefaultClassLoader.java:43) ~[dozer-5.5.1.jar:na]
    at org.dozer.util.MappingUtils.loadClass(MappingUtils.java:224) ~[dozer-5.5.1.jar:na]
    at org.dozer.loader.DozerBuilder$MappingBuilder.classA(DozerBuilder.java:129) ~[dozer-5.5.1.jar:na]
    at org.dozer.loader.xml.XMLParser.parseMapping(XMLParser.java:190) ~[dozer-5.5.1.jar:na]
    at org.dozer.loader.xml.XMLParser.read(XMLParser.java:137) ~[dozer-5.5.1.jar:na]
    at org.dozer.loader.xml.XMLParser.read(XMLParser.java:43) ~[dozer-5.5.1.jar:na]
    at org.dozer.loader.xml.MappingStreamReader.read(MappingStreamReader.java:51) ~[dozer-5.5.1.jar:na]
    at org.dozer.loader.xml.MappingFileReader.read(MappingFileReader.java:58) [dozer-5.5.1.jar:na]
    at org.dozer.DozerBeanMapper.loadFromFiles(DozerBeanMapper.java:227) [dozer-5.5.1.jar:na]
Caused by: java.lang.ClassNotFoundException: models.location.Location
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_25]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_25]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_25]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_25]
    at java.lang.Class.forName0(Native Method) ~[na:1.8.0_25]
    at java.lang.Class.forName(Class.java:344) ~[na:1.8.0_25]
    at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:909) ~[commons-lang3-3.4.jar:3.4]
    at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:943) ~[commons-lang3-3.4.jar:3.4]
```

**Comment by FrEaKmAn** [comment] 2015-10-09 11:38
Same problem here. I'm also using Play2.4. Reverting back to 5.4. version solved the problem.

**Comment by dosten-xx** [comment] 2015-12-22 20:43
This happens using karaf 4.0.1 as well

**Comment by christianmenz** [comment] 2016-04-07 21:19
Took me quite a while to figure out what the problem was for me. I can't tell for sure as I don't know your exact setup, but maybe this helps other people searching for a solution. I'm using dozer in an enterprise application and dozer jar is loaded by the EARLibClassLoader (the app by the EARAppClassLoader).

Dozer does this: 

`DozerClassLoader classLoader = new DefaultClassLoader(getClass().getClassLoader());`

Which imho is the wrong classloader for loading the classes in my dozer mapping file. I fixed this by adding this line of code before creating the mapper:

`BeanContainer.getInstance().setClassLoader(new DefaultClassLoader(Thread.currentThread().getContextClassLoader()));`

**Comment by venkatshan** [comment] 2016-12-12 18:54
Thanks. Your solution worked for me for Dozer child object mapping class not found error in PlayFramework.

**Comment by paksboda** [comment] 2017-01-25 07:44
@christianmenz Thanks for your comment and it works for me. Are we planning to fix this in new version of dozer?

**Comment by garethahealy** [comment] 2017-04-05 13:02
https://github.com/DozerMapper/dozer/pull/249

**Comment by garethahealy** [comment] 2017-04-05 13:02
Duplicate of https://github.com/DozerMapper/dozer/issues/248

**Closed by garethahealy** 2017-04-05 13:02 UTC
