### ISSUE TITLE
Migrate site from SF to GitHub

### ISSUE THREAD

**Issue by buzdin** [DozerMapper/dozer#342] opened 2017-04-19 10:43 UTC
At the moment documentation is still hosted on legacy SF website [http://dozer.sourceforge.net/]

It should be migrated to GitHub Pages.

**Comment by garethahealy** [comment] 2017-04-19 10:44
@buzdin ; thats the plan :)

**Comment by orange-buffalo** [comment] 2017-05-25 17:29
Guys, if you could create a repo for Dozer on GitHub Pages, I would be happy to help with migration. 

BTW, some parts of the website are duplicated in wiki section of GitHub repo:
https://github.com/DozerMapper/dozer/wiki/Why-Map%3F
https://github.com/DozerMapper/dozer/wiki/Getting-Started
https://github.com/DozerMapper/dozer/wiki/General-Usage
Probably it makes sense to remove them from wiki to maintain only one single source of documentation. 

Another closely related topic is the PDF guide. If documentation is migrated to GitHub Pages, do you have ideas how to deal with this?

**Comment by garethahealy** [comment] 2017-05-25 17:35
@orange-buffalo ; i'd prefer if the wiki was removed, since it duplicates content (dont think i have permission to remove though).

I would like all docs to be kept in:
- https://github.com/DozerMapper/dozer/tree/master/docs/asciidoc

And then built using gitbooks, which can be pushed to github pages. That way we only have 1 place for everything and its in an easy viewable / editable format, i.e.: ascidoc

**Comment by garethahealy** [comment] 2017-05-25 17:40
@buzdin ; can you create a pages repo? or give me repo creation rights.
- https://pages.github.com/

**Comment by garethahealy** [comment] 2017-05-25 18:05
https://github.com/DozerMapper/DozerMapper.github.io

**Comment by garethahealy** [comment] 2017-05-27 08:56
Added first draft:
- https://dozermapper.github.io/

**Comment by garethahealy** [comment] 2017-05-27 08:56
TODO: Push docs from dozer repo to gh-pages.

**Comment by orange-buffalo** [comment] 2017-05-27 09:04
I see one complication with automatic publishing to GitHub Pages and wanted to ask your opinions. 

There are two use-cases for documentation updates:
*  Improvements / fixes for documentation of existing functionality. 
This would be perfectly safe, useful and convenient to automatically push updated docs to GitHub Pages.
* Documentation of new functionality. 
This is exactly where I see some issues. If documentation is automatically pushed to GitHub Pages, users will see new features before they are available in any released version. So the online doc will not be aligned with code available to Dozer users. 

Do you have ideas how to deal with the second use case?

**Comment by orange-buffalo** [comment] 2017-05-27 11:14
One more thing. I am currently trying to automate doc build with Maven. I have generated html pages from `adoc` files in `website` folder using `gitbook`, but got different result from what is currently deployed to GitHub Pages. I used `gitbook` because found scripts for this tools in `docs/build-gitbook.sh`. @garethahealy, have you generated website using `gitbook`? if yes, could you please share the config so I can embed it into automatic build? 

Also I am wondering about two folders with documentation - one is `website`, another is `docs`. Would it make sense to merge them to have one source for online documentation?

**Comment by garethahealy** [comment] 2017-09-06 17:39
@orange-buffalo ; anything else needed for this issue? or can it be closed?

**Comment by orange-buffalo** [comment] 2017-09-07 05:45
@garethahealy I believe initial goal of this issue is achieved. I do not know if you plan to fully automate the process of documentation generation and publishing. Probably if yes, this will be a topic for another issue (btw, here is a quite nice Travis integration script https://gist.github.com/domenic/ec8b0fc8ab45f39403dd). 

Another thing is that once all the relevant documentation is on GitHub Pages, the Wiki section of GitHub project could be disabled to not confuse users. 

Other than that, nothing else from my side.

**Comment by garethahealy** [comment] 2017-09-10 20:26
Have removed the wiki pages as the content was just duplicate of GH-pages.

**Comment by orange-buffalo** [comment] 2017-09-12 05:42
Thanks!

**Comment by jbq** [comment] 2018-02-24 07:47
The SF site at http://dozer.sourceforge.net/ should be removed, or a big deprecation notice added, in favor of the github repo landing page.  This old site leads to believe the project is dead!

**Comment by garethahealy** [comment] 2018-02-24 10:22
@buzdin needs to do that @jbq, as i dont have access to SF

**Comment by buzdin** [comment] 2018-02-26 07:48
Should I completely remove that project on SF @garethahealy ?

**Comment by garethahealy** [comment] 2018-02-26 07:59
@buzdin ; if you still have access to the FTP, can you download the site, zip it, and attach? I'll modify so that all pages redirect via JS to github.

If not, then, yes, remove please.

**Comment by vadeg** [comment] 2018-04-23 19:02
How about to migrate documentation to GitHub Pages and use [MkDocs](http://www.mkdocs.org) as a template for documentation?

**Comment by garethahealy** [comment] 2018-04-23 19:42
@vadeg ; we already use GH pages and ascidoc with gitbook.
- https://dozermapper.github.io/gitbook/index.html

**Closed** 2020-07-13 08:58 UTC
Labels: documentation
