### ISSUE TITLE
Configuring the classloader is a nightmare in dozer 5.5.1

### ISSUE THREAD

**Issue by josechillan** [DozerMapper/dozer#193] opened 2014-09-05 14:24 UTC
I have a special case where I use dozer in a webapp and several configurations in different projets, each of them having their own classloader. The point is that when configured in Spring with DozerBeanMapper, dozer use by default the class loader of the Dozer classes to load the classes in the configuration. It is said that this can be configured, but the method DozerBeanMapper.init() is private and uses no classloader. The only way is to use a configuration file and define a system property dozer.configuration but first this is for the whole JVM (and I want another beahviour in my webapp), and second, it has no effect unless DozerInitializer.getInstance().init(Classloader) is invoked, which is not the case of DozerBeanMapper.
Last, I don't understand why to provide a custom classloader, where have to define another implementation of DozerClassLoader (this special code in  DozerInitializer.registerClassLoader() that makes the classloader argument useless if the DozerClassLoader has not been specified).
To solve this problem, I have to copy a bunch of code and modify it in place.

**Comment by garethahealy** [comment] 2017-04-04 15:27
Related to https://github.com/DozerMapper/dozer/issues/22

**Comment by garethahealy** [comment] 2017-05-31 20:39
Closing as duplicate of #22

**Closed by garethahealy** 2017-05-31 20:39 UTC
