### ISSUE TITLE
Dozer mapping stops working

### ISSUE THREAD

**Issue by heneke** [DozerMapper/dozer#118] opened 2013-07-03 09:33 UTC
After a short amount of time (varies between hours up to one day), dozer mapping stop working with

org.dozer.MappingException: java.lang.NoSuchMethodException: Unable to determine write method for Field: 'xxxxx' in Class: class a.b.c.FooBar
        at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:82)
        at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.invokeWriteMethod(GetterSetterPropertyDescriptor.java:261)
        at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.setPropertyValue(GetterSetterPropertyDescriptor.java:101)
        at org.dozer.fieldmap.FieldMap.writeDestValue(FieldMap.java:94)
        at org.dozer.MappingProcessor.writeDestinationValue(MappingProcessor.java:870)
        at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:337)
        at org.dozer.MappingProcessor.mapField(MappingProcessor.java:276)
        at org.dozer.MappingProcessor.map(MappingProcessor.java:245)
        at org.dozer.MappingProcessor.map(MappingProcessor.java:187)
        at org.dozer.MappingProcessor.map(MappingProcessor.java:124)
        at org.dozer.MappingProcessor.map(MappingProcessor.java:119)
        at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:111)

This is Dozer 5.3.2 on Java 1.7, but happens with 5.4.x also. It's never the same target class or field that fails.

This was already reported here: http://sourceforge.net/p/dozer/bugs/372/

**Comment by kumaraln** [comment] 2015-01-07 03:23
we have this in our production system as well and we turned off this feature for now. so updating the beantutil to its latest version fixes this issue? or do we need to upddate both dozer and bean util?

**Comment by waldemar-schneider** [comment] 2015-03-09 16:09
After we moved to a new BeanUtils Version (1.9.2) and moved getter and setter for the id (for more info, look at [my previous post ](https://github.com/DozerMapper/dozer/issues/118#issuecomment-67332345) )into the same interface, this issue is no longer existent in our environment.

**Comment by Sukesh-Alluri** [comment] 2015-10-05 20:08
Is there a possible way of not having to move getter and setter to same base as we've an usage where we override the getters and setters in children in source pojo but not in destination pojo?

**Comment by pm-riyanka-dagaonkar** [comment] 2015-12-17 07:53
Hi, We have been using dozer version 5.2.2 in our application and we faced this issue recently on production. It is not reproducible on local set up. Can anyone confirm if the issue is fixed in the latest release 5.5.1 ? Or is there any other way of fixing it?

**Comment by Tim-Craig** [comment] 2016-01-15 20:00
I see this Pull request that it a fix for this issue
https://github.com/DozerMapper/dozer/commit/2cd932235358bee74468867285c98c5eacdcdaca

I see it has come in after the 5.5.1 release.  Is there going to be a new release so this bug fix can come out in an official build?  If not, is the current master branch of this repo considered stable enough for people who use dozer in a production environemnet?

**Comment by Naa007** [comment] 2016-04-25 13:58
Hi we are using dozer 5.2.2 and getting this exception...

  MapId: null
  Type: null
  Source parent class: org.akc.ngen.domain.impl.EventEntity
  Source field name: eventPlanPendingEntities
  Source field type: class org.hibernate.collection.PersistentBag
  Source field value: Unable to determine source field value
  Dest parent class: org.akc.ngen.biz.model.Event
  Dest field name: editMessages
  Dest field type: java.util.List

Getters and Setters are in abstract super class. 

We are facing the issue only in Production not able to reproduce in Local.
Is it fixed ? Or any alternative way to fix it?

**Comment by jsebfranck** [comment] 2016-05-25 14:14
Hi, same problem for me, dozer mappings are instable in preproduction. When will you release the version 5.5.2 ? Or at least in beta ? Otherwise I will have to compile myself the trunk and push it in our nexus instance...

**Comment by shakunahuja** [comment] 2016-12-22 12:00
Hi ,
Same Problem for me ,Any temporary solution??

**Comment by MarshallShi** [comment] 2016-12-29 05:49
Hi there, any update on this issue? Is this issue fixed on 5.5.1?

**Comment by shakunahuja** [comment] 2016-12-29 07:43
My problem has been solved by replacing the common beanutils jar version to 1.8.3 (working fine from last two days after changing the mention beanutils version) and I am using dozer 5.3.2 version.Basically beanutils version mentioned in dozer pom.

and second thing getter setter of a variable should not be in two diff  interfaces in its respective hierarchy.

**Comment by nine99systems** [comment] 2017-02-14 10:15
Hi ,
Facing problem with JAXB maping without setter for collection.
Here is the stack trace : 

2017-02-14 18:11:58,241 ERROR [IBSOutboundProcess:124]: IBSOutboundProcessor  DataAccessException occured  for batch : 6ab7f78e-d75f-4866-b2ad-981597aa2d8f
java.lang.NullPointerException
	at org.dozer.util.ReflectionUtils.invoke(ReflectionUtils.java:329)
	at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.writeDeepDestinationValue(GetterSetterPropertyDescriptor.java:232)
	at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.setPropertyValue(GetterSetterPropertyDescriptor.java:96)
	at org.dozer.fieldmap.FieldMap.writeDestValue(FieldMap.java:96)
	at org.dozer.MappingProcessor.writeDestinationValue(MappingProcessor.java:939)
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:368)
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
	at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
	at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196)
	at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:104)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:99)
	at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
	at com.dhl.gcdb.intg.outbd.ibs.IBSOutboundProcess.generaetCMFTaskFeed(IBSOutboundProcess.java:162)
	at com.dhl.gcdb.intg.outbd.ibs.IBSOutboundProcess.processIBSOutbound(IBSOutboundProcess.java:91)
	at com.dhl.gcdb.intg.outbd.ibs.IBSOutboundProcess$$FastClassByCGLIB$$45b1bb4c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:634)
	at com.dhl.gcdb.intg.outbd.ibs.IBSOutboundProcess$$EnhancerByCGLIB$$1cad4035.processIBSOutbound(<generated>)




Some sample mapping  : 


`    <field>
      <a>collectionSource[0].fieldAbc</a>
      <b>collectionDestination[0].fieldXyz</b>
      <b-deep-index-hint>xxx.abc.pckg.ClassExample</b-deep-index-hint>
    </field>`

**Comment by gauravtyagi77** [comment] 2017-05-09 09:59
I am also facing the same issue even after commonbeanutils-1.8.3 and dozer 5.3.2 and abstract setter is also in only one interface in interface hierarchy . Have anyone found any other solution for this.

org.dozer.MappingException: java.lang.NoSuchMethodException: Unable to determine write method for Field: 'id' in Class: class

**Comment by garethahealy** [comment] 2017-05-09 10:03
@gauravtyagi77 ; can you build from latest source and retest please?

**Comment by garethahealy** [comment] 2017-05-31 21:16
Please re-test with 6.0.0

**Closed by garethahealy** 2017-05-31 21:16 UTC

**Comment by asadabdin** [comment] 2018-04-16 07:33
try adding default constructor in your class.
